name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: windows-latest  # Use Windows to match your GCC/MinGW setup

    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Match your development environment

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          pip install numpy  # Required by pyproject.toml

      # Install MinGW for GCC
      - name: Install MinGW
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: mingw-w64-x86_64-gcc

      # Build the C extension manually
      - name: Build calculator.pyd
        run: |
          gcc -Wall -Wextra -fPIC -IC:\Users\runneradmin\AppData\Local\Programs\Python\Python310\include -c src/c/calculator.c -o src/c/calculator.o
          gcc -shared -o calculator.pyd src/c/calculator.o -LC:\Users\runneradmin\AppData\Local\Programs\Python\Python310\libs -lpython310

      # Build the package
      - name: Build distribution
        run: |
          python -m build

      # Run tests
      - name: Run tests
        run: |
          pip install dist/c_python_calculator-1.0.0.tar.gz
          python test.py

      # Code scanning with CodeQL
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python, c  # Scan both Python and C code

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      # Optional: Deploy to GitHub Release
      - name: Upload artifacts to GitHub Release
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/c_python_calculator-1.0.0.tar.gz
            dist/c_python_calculator-1.0.0-py3-none-any.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
